export default actionTypes = {
    CHANGE_LOGIN: 'CHANGE_LOGIN',
    CHANGE_LOGIN_ASYNC: 'CHANGE_LOGIN_ASYNC',
    SET_THEME: 'SET_THEME',
    GET_THEME: 'GET_THEME',
    USE_ONLINE_DATA: 'USE_ONLINE_DATA',
    SET_CUSTOM_KEY: 'SET_CUSTOM_KEY',
    GET_CUSTOM_KEYS: 'GET_CUSTOM_KEYS',
    SET_FAVORITE:'SET_FAVORITE',
    GET_FAVORITE:'GET_FAVORITE'
  }